-- ALIAS AS
-- LLAMA A UNA TABLA O COLUMNA, ES PARA SIMPLIFICAR LOS NOMBRE 
-- SELECT COLUMNA AS ALIASCOLUMNA FROM TABLA 

SELECT * FROM PERSONAS
SELECT APELLIDO1 FROM PERSONAS
SELECT APELLIDO1 FROM PERSONAS WHERE APELLIDO1 = "PEREZ"
SELECT APELLIDO1 AS AP1 FROM PERSONAS WHERE AP1 = "PEREZ"