-- AUTOINCREMENT 
-- GENERA UN NUMERO UNICO AL AGREGAR UN DATO EN LA TABLA, EL VALOR INICIAL ES 1 Y SE UTILIZA PRIMARY KEY

CREATE TABLE TABLA1 (
	ID_TABLA1 INTEGER PRIMARY KEY AUTOINCREMENT,
	NOMBRE VARCHAR NOT NULL
	)
	
INSERT INTO TABLA1 VALUES (NULL, "OBJETO 1")
INSERT INTO TABLA1 VALUES (NULL, "OBJETO 2")
INSERT INTO TABLA1 (NOMBRE) VALUES ("ANTHONY")
SELECT * FROM TABLA1
