-- BETWEEN 
-- SIRVE PARA BUSCAR RESULTADOS POR RANGOS ENTRE DOS VALORES
-- SELECT * FROM TABLA WHERE COLUMNA BETWEEN VALOR1 AND VALOR2
-- BUSCAR A LAS PERSONAS QUE TENGAN UNA EDAD ENTRE LOS 20 Y 50

SELECT * FROM PERSONAS WHERE EDAD BETWEEN "20" AND "50" 