-- CREATE TABLE
-- CREA UNA TABLA EN UNA BASE DE DATOS
-- CREATE TABLE TABLA (COLUMNA1 TIPO, COLUMNA2 TIPO,....)

CREATE TABLE BEBIDAS (ID INTEGER, NOMBRE TEXT)

SELECT * FROM BEBIDAS

INSERT INTO BEBIDAS VALUES (1, "PEPSI")