-- Ejercicio 14
-- Insertar en la tabla "SALARIOS" creada anteriormente, 2 filas
-- con los siguientes datos:
-- NOMBRE="ANTONIO", EDAD= 30, DIRECCION = "CALLE 1", SALARIO= 2000.00
-- NOMBRE="JUAN", EDAD= 40, DIRECCION = "CALLE 2", SALARIO= 3000.00
DROP TABLE SALARIOS
CREATE TABLE SALARIOS (ID INTEGER PRIMARY KEY AUTOINCREMENT, NOMBRE TEXT NOT NULL, EDAD INTEGER NOT NULL, DIRECCION CHAR (50), SALARIO REAL)
INSERT INTO SALARIOS ( NOMBRE, EDAD, DIRECCION, SALARIO) VALUES ( "ANTONIO", 30, "CALLE 1",2000.00 )
INSERT INTO SALARIOS  ( NOMBRE, EDAD, DIRECCION, SALARIO) VALUES ( "JUAN", 40, "CALLE 2",3000.00 )