-- Seleccionar el nombre, el primer apellido , edad y el departamento
-- de las personas cuyo nombre sea ANTONIO
-- y el resultado ordelarlo por departamento

SELECT NOMBRE, APELLIDO1, EDAD, DEP FROM PERSONAS JOIN DEPARTAMENTOS WHERE NOMBRE="ANTONIO" ORDER BY DEP

SELECT NOMBRE, APELLIDO1, EDAD, DEPARTAMENTO 
FROM PERSONAS JOIN DEPARTAMENTOS WHERE PERSONAS.DEP = DEPARTAMENTOS.DEP  
AND NOMBRE="ANTONIO"
ORDER BY DEPARTAMENTO