-- IN
-- PERMITE SELECCIONAR MULTIPLES VALORES EN WHERE ES DECIR CONSULTA EN UNA LISTA DE VALORES
-- BUSCAR LAS PERSONAS CON APELLIDO2 BENITO Y GONZALEZ

SELECT * FROM PERSONAS WHERE APELLIDO2 IN ("BENITO", "GONZALEZ")

-- BUSCAR LAS PERSONAS CON EDAD 23 Y 56
SELECT * FROM PERSONAS WHERE EDAD IN ("23","56")



