-- JOIN 
-- Permite consultar datos de dos o mas tablas
-- SELECT * FROM TABLA1 JOIN TABLA2 WHERE TABLA1.COLUMNA1 = TABLA2.COLUMNA1
-- LA TABLA PERSONAS SE RELACIONA CON LA TABLA DEPARTAMENTOS, POR ENDE PODEMOS SACAR INFORMACION 

SELECT * FROM PERSONAS JOIN DEPARTAMENTOS WHERE PERSONAS.DEP = DEPARTAMENTOS.DEPARTAMENTO 
SELECT NOMBRE, APELLIDO1, DEPARTAMENTO FROM PERSONAS JOIN DEPARTAMENTOS WHERE PERSONAS.DEP = DEPARTAMENTOS.DEP