-- like
-- SE USA EN WHERE PARA BUSCAR UN PATRON UTILIZANDO EL OPERADOR %% ENTRE COMILLAS
-- BUSCAMOS EN LA COLUMNA NOMBRE LOS NOMBRES QUE TENGA S

SELECT * FROM PERSONAS WHERE NOMBRE LIKE "%S%"

-- QUE EMPIEZE POR P 
SELECT * FROM PERSONAS WHERE APELLIDO2 LIKE "P%"
-- QUE termine POR Pz
SELECT * FROM PERSONAS WHERE APELLIDO2 LIKE "%z"