-- NOT NULL
-- RESTRINGE QUE EL CAMPO DE UNA COLUMNA A VALORES VACIOS
-- CREATE TABLE TABLA (COLUMNA1 TIPO, COLUMNA2 TIPO2 NOT NULL)
-- CREAR UNA TABLA CUALQUIERA QUE RESTRUNJA EN SUS COLUMNAS VALORES VACIOS

CREATE TABLE RELOJES (ID INTEGER PRIMARY KEY AUTOINCREMENT, NOMBRE TEXT NOT NULL, PRECIO FLOAT NOT NULL )
DROP TABLE RELOJES
SELECT * FROM RELOJES 
INSERT INTO RELOJES VALUES (4 ,"SS",0.5)