--SELECT PARA CONSULTAS--
SELECT DEPARTAMENTO FROM DEPARTAMENTOS

--DISTINCT PARA SACAR VALORES DISTINTOS ----
SELECT  DISTINCT DEPARTAMENTO FROM DEPARTAMENTOS


-- WHERE FILTROS O CONDIFICONES--
SELECT * FROM DEPARTAMENTOS  WHERE DEPARTAMENTO = "INFORMATICA"


-- WHERE FILTROS O CONDIFICONES--
SELECT NOMBRE FROM PERSONAS WHERE DEP = 2

-- AND OR PARA FILTAR RESULTADOS CON  DOS CONDICIONES
-- AND MUESTRA EL RESULTADOCUANDO SE CUMPLA AMBAS CONDICIONES--
SELECT * FROM PERSONAS WHERE DEP = 2 AND NOMBRE= "ANTONIO" 
-- OR MUESTRA EL RESULTADO CUAN SE CUMPLA ALGUNA DE LAS DOS CONDICIONES --
SELECT * FROM PERSONAS WHERE DEP = 2 OR NOMBRE = "ANTONIO"


-- ORDER BY ORDERNAR LOS RESULTADOS DE UNA CONSULTA SEGUN EL VALOR DE UNA COLUMNA ESPECIFICADA--
SELECT * FROM PERSONAS ORDER BY EDAD DESC

SELECT * FROM PERSONAS ORDER BY APELLIDO1

-- INSERT INTO  INSERTAR ELEMENTOS DE UNA TABLA --
SELECT * FROM PERSONAS 
INSERT INTO  PERSONAS VALUES(5, "PEPE", "CARTEJO", "PEREZ", "12345678", 13, 2, 0)

--UPDATE PARA MODIFICAR VALORES EN UNA TABLA --
SELECT * FROM PERSONAS 
UPDATE PERSONAS SET EDAD= 23 WHERE NOMBRE = "PEPE" 
UPDATE PERSONAS SET APELLIDO1= "SANCHEZ" WHERE NOMBRE = "PEPE" 

-- DELETE BORRA FILAS DE UNA TABLA --

DELETE FROM PERSONAS WHERE NOMBRE = "PEPE"







