-- UNIQUE
-- La restriccion unique identifica de manera unica a cada fila de una tabla puede haber varias restrucciones
-- CREATE TABLE TABLA1 (ID INTEGUER UNIQUE, NOMBRE TEXT, PRECIO INTEGER)

CREATE TABLE CEDULA (ID INTEGER UNIQUE , NUMERO INTEGER NOT NULL UNIQUE)
INSERT INTO CEDULA VALUES (3, 80228496817)
SELECT * FROM CEDULA
DROP TABLE CEDULA